//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataKendaraan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vehicle
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Data Tidak Boleh Kosong")]
        public string RegistrationVehicleNumber { get; set; }
        [Required(ErrorMessage = "Data Tidak Boleh Kosong")]
        public string OwnerName { get; set; }

        public string Address { get; set; }
        public string Brand { get; set; }
        [Range(1000, 9999, ErrorMessage = "Harus 4 digit angka")]

        public Nullable<int> ProductionYear { get; set; }

        public Nullable<int> CylinderCapacity { get; set; }
        public string VehicleColor { get; set; }
        public string Fuel { get; set; }
    }
}
